config/routes.rb
require 'resque/server'
HelpLine::Application.routes.draw do
  mount Resque::Server, :at => "/resque"
  root 'welcome#home'
  get 'sign-in',        to: 'welcome#home'
  post '/sign_in',      to: 'welcome#sign_in', as: :sign_in
  post '/sign_out',     to: 'welcome#sign_out', as: :sign_out

  get '/sign_up',       to: 'adies#new', as: :sign_up
  post '/sign_up',      to: 'adies#create', as: :add_adie # make only admin accessible?

  get '/analysis',      to: 'problems#analysis'
  get '/adies',         to: 'adies#index'

  get '/help_me',       to: 'problems#new'
  post '/help_me',      to: 'problems#create', as: :new_problem
  get '/problems',      to: 'problems#index', as: :problems
  get '/problems/:id',  to: 'problems#show', as: :problem
  post '/ratings/new',  to: 'ratings#create', as: :ratings
  post '/problems/:id', to: 'problems#update', as: :helped

  get '/profile',       to: 'adies#show', as: :profile
  patch '/profile',     to: 'adies#update', as: :set_profile
  patch '/reset',       to: 'adies#new_password', as: :forgot_password

  get '/status',        to: 'status#index'

  post '/csv',          to: 'adies#bulk_upload'
end

app/controllers/adies_controller.rb
class AdiesController < ApplicationController
  skip_filter :redirect_if_not_signed_in, only: [:new_password]
  require 'csv'

  def index
    @adies = Adie.where(current: true)
  end

  def new
    @admin = Adie.find(session[:adie_id])
    if @admin.admin == true
      @adie = Adie.new
    else
      redirect_to problems_path
    end
  end

  def create
    @adie = Adie.new(adie_params)
    if @adie.save
      redirect_to '/problems'
    else
      render :new
    end
  end

  def show
    @adie = Adie.find(session[:adie_id])
  end

  def update
    @adie = current_adie
    @adie.update(adie_params)
    if @adie.save
      flash[:notice] = "Thanks for updating your info!"
      render :json => { password: @adie.password }
    else
      render :json => { :message => @adie.errors.full_messages }, status: 400
    end
  end

  def new_password
    adie = Adie.where(email: params[:adie][:email]).first
    if adie
      adie.create_random_password
      render :json => {}, status: 200
    else
      render :json => {}, status: 400  
    end
  end

  def bulk_upload
    Adie.bulk_upload(params['adies'])
    redirect_to problems_path
  end

  private

  def adie_params
    params.require(:adie).permit(:name,
                                 :password,
                                 :password_confirmation,
                                 :adatar,
                                 :ta,
                                 :email,
                                 :current)
  end

end

app/views/adies/_bulk_upload.html.erb
<div class='uploads'>
  <h3>
    Or All At Once!
  </h3>
  <%= form_tag('/csv', multipart: true) do %>
    <div class = "field">
        <%= label_tag "Upload CSV of Adies:" %>
        <%= file_field_tag :adies %>
    </div>
    <div class='field'>
      <%= submit_tag "Submit" %>
    </div>
  <% end %>
</div>

app/views/adies/_form.html.erb
<% @adie.errors.full_messages.each do |message| %>
  <% message %>
<% end %>

<h3>Create One Adie At A Time ...</h3>
<div>

  <%= form_for @adie, url: add_adie_path do |f|%>
    <div class ="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class='field'>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class ="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class ="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class= 'field'>
      <%= f.label 'TA?' %>
      <%= f.check_box :ta %>
    </div>
    <div class = "field">
      <%= f.label "Upload local file:" %><br />
      <%= f.file_field :adatar %>
      <%= f.hidden_field :adatar_cache %>
    </div>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/adies/_password_request.html.erb
<p>Please give us your Helplist email, and we'll send you a new password.</p>
<%= form_for @adie, url: add_adie_path do |f|%>
    <div class='field'>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'inputField'%>
    </div>
<% end %>

app/views/adies/_reset.html.erb
<div class='alerts'>
</div>
<div class="errors">
  <ul class='listErrors'>
  </ul>
</div>
<%= form_for @adie, url: set_profile_path do |f|%>
  <div class='field'>
    <%= f.label :email, class: 'email' %>
    <%= f.text_field :email, class: 'email_input' %>
  </div>
  <div class='field'>
    <%= f.label :password, "New password:", class: 'newPass' %>
    <%= f.password_field :password  %>
  </div>
  <div class='field'>
    <%= f.label :password_confirmation, "Confirm your new password", class: 'confirm' %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class = "field">
    <%= f.label "Upload local file:" %>
    <%= f.file_field :adatar %>
    <%= f.hidden_field :adatar_cache %>
  </div>
<% end %>

app/views/adies/index.html.erb
<ol>
  <% @adies.each do |adie| %>
    <li><%= adie.name %>
    <%= image_tag(adie.adatar_url, :width => 400) if adie.adatar.present? %></li>
  <% end %>

</ol>

<%= link_to "Back to sign in page", root_url %>

app/views/adies/new.html.erb
<%= render 'form' %>
<br><br>
<%= render 'bulk_upload' %>

app/views/adies/show.html.erb
<%= render 'reset' %>