config/routes.rb
require 'resque/server'
HelpLine::Application.routes.draw do
  mount Resque::Server, :at => "/resque"
  root 'welcome#home'
  get 'sign-in',        to: 'welcome#home'
  post '/sign_in',      to: 'welcome#sign_in', as: :sign_in
  post '/sign_out',     to: 'welcome#sign_out', as: :sign_out

  get '/sign_up',       to: 'adies#new', as: :sign_up
  post '/sign_up',      to: 'adies#create', as: :add_adie # make only admin accessible?

  get '/analysis',      to: 'problems#analysis'
  get '/adies',         to: 'adies#index'

  get '/help_me',       to: 'problems#new'
  post '/help_me',      to: 'problems#create', as: :new_problem
  get '/problems',      to: 'problems#index', as: :problems
  get '/problems/:id',  to: 'problems#show', as: :problem
  post '/ratings/new',  to: 'ratings#create', as: :ratings
  post '/problems/:id', to: 'problems#update', as: :helped

  get '/profile',       to: 'adies#show', as: :profile
  patch '/profile',     to: 'adies#update', as: :set_profile
  patch '/reset',       to: 'adies#new_password', as: :forgot_password

  get '/status',        to: 'status#index'

  post '/csv',          to: 'adies#bulk_upload'
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  validates :type,        presence: true
  validates :estimate,    presence: true
  validates :description, presence: true
  validates :adie_id,     presence: true
  has_one :rating

  belongs_to :adie
  self.inheritance_column = nil

  def self.find_room(room = Figaro.env.campfire_default_room)
    campfire = Tinder::Campfire.new Figaro.env.campfire_subdomain,
                                    token: Figaro.env.campfire_token

    @room = campfire.find_room_by_name(room)
  end

  def self.report(problem, sound = 'trombone')
    @room ||= find_room
    @room.speak "#{Adie.find(problem.adie_id).name} is having a " +
                     "problem with #{problem.type}. The problem is " +
                     "#{problem.description}. Estimated time to fix: " +
                     "#{problem.estimate} -- http://helplist.herokuapp.com/problems"
    @room.play sound unless sound.nil?
  end

  def self.high_ratings
    includes(:ratings).where(:"ratings.rating" => 5)
  end

  def self.reminder
    where(helped: 'needs help').each do |problem|
      if wait_time > 600 && wait_time < 1200
        # (ノ°□°)ノ彡 ┻━┻
        report("#{Adie.find(problem.adie_id).name} STILL needs help. Can " +
                 "someone check it out, already? " +
                 "-- http://helplist.herokuapp.com/problems",
               'crickets')
      elsif wait_time > 1200
        report("Ahem. #{Adie.find(problem.adie_id).name} is STILL waiting. " +
                 "Get ON this -- http://helplist.herokuapp.com/problems",
               'crickets')
      end
    end
  end

  def wait_time
    Time.now - created_at
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy, :report]

  def index
    @problems = Problem.where.not(helped: 'helped')
    @problem = Problem.new
    @adie = current_adie
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = current_adie.problems.create(problem_params)

    if @problem.save
      Problem.report(@problem) if Rails.env.production?
      flash[:notice] = "We will be with you shortly!"
      render :json => {}
    else
      render :json => { :message => @problem.errors.full_messages }, status: 400
    end
  end

  def show
    @rating = Rating.new
  end

  def update
    if @problem.helped == 'needs help'
      @problem.update(helped: 'being helped')
    elsif @problem.helped == 'being helped'
      @problem.update(helped: 'helped')
    end
    redirect_to problems_path
  end

  def analysis
    @problems = Problem.where(helped: 'helped')
  end

private

  def set_problem
    @problem=Problem.find(params[:id])
  end

  def problem_params
    params.require(:problem).permit(:adie_id,
                                    :type,
                                    :description,
                                    :estimate,
                                    :helped)
  end
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/views/problems/_form.html.erb
<div class="errors">
  <ul class='listErrors'>
  </ul>
</div>
<div>
<%= form_for @problem, url: new_problem_path do |f| %>
<div class='field'>
  <%= f.label :type %><br>
  <%= f.select(:type, ['Rails','Ruby','CSS/HTML','JavaScript','Other'], class: 'item') %> <br><br>
</div>
<div class='field'>
  <%= f.label :description, "Tell me your woes:" %><br>
  <%= f.text_area :description, class: "form-control", rows: "5"%><br><br>
</div>
<div class='field'>
  <%= f.label :estimate, "Estimated time to solve the problem:" %><br>
  <%= f.select(:estimate, ['5 minutes','20 minutes','45 minutes','possibly hours','Not Sure','someone have mercy on my soul'])%> <br><br>
</div>
<% end %>

app/views/problems/_new_problem.html.erb
<div class="modal fade" id="newProblemModal" tabindex="-1" role="dialog" aria-labelledby="newProblemLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="fontFancy">What seems to be the problem?</h4>
      </div>
      <div class="modal-body">
        <%= render 'problems/form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id='getHelp'>Help, plz.</button>
      </div>
    </div>
  </div>
</div>

app/views/problems/_profile.html.erb
<div class="modal fade" id="profileModal" tabindex="-1" role="dialog" aria-hidden="true" data-email=<%= @adie.email.present? %>>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="fontFancy">Please set your profile information</h4>
      </div>
      <div class="modal-body">
        <%= render 'adies/reset' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="resetProfile">Reset</button>
      </div>
    </div>
  </div>
</div>

app/views/problems/_ratings_form.html.erb
<%= form_for @rating do |f| %>
  <%= f.label 'Who helped you?' %>
  <%= f.text_field :helper %>
  <br>
  <%= f.label "How would you rate the solution at which you arrived? (IE, how good is the solution?)" %>
  <%= f.select(:rating, [1,2,3,4,5]) %> 
  <br>
  <%= f.label "Please describe the solution" %>
  <%= f.text_area :solution %>
  <br>
  <%= f.label "Sooooo what's your satisfaction? (IE, how satisfied are you with the actual help you were given)" %>
  <%= f.select(:satisfaction, [1,2,3,4,5]) %> 

  <%= f.hidden_field :problem_id, value: @problem.id %>

  <%= f.submit %>

<% end %>

app/views/problems/analysis.html.erb
<h3> Give us the digits </h3>

<table>
  <thead>
    <tr>
      <th> Adie, holla! </th>
      <th> Type of problem </th>
      <th> Time Estimate </th>
      <th> Description </th>
      <th> Time Created </th>
      <th> Time Helped </th>
      <th> Time it took to be helped </th>
    </tr>
  </thead>
  <tbody> 
    <% @problems.sort_by {|problem| problem.created_at}.each do |problem| %>
      <tr>
          <td><%= Adie.find(problem.adie_id).name %></td>
          <td><%= problem.type %></td>
          <td><%= problem.estimate %></td>
          <td><%= problem.description %></td>
          <td><%= problem.created_at %></td>
          <td><%= problem.updated_at %></td>
          <td><%= ChronicDuration.output(problem.updated_at - problem.created_at) %>
          </td>
      </tr>
    <% end %> 
    
  </tbody>
   
</table>

app/views/problems/edit.html.erb
<%= render 'form' %>

app/views/problems/index.html.erb
<!-- <meta http-equiv="refresh" content="60" /> -->
<div class='center'>
  <h4 id="fontFancy"> Hi <%= current_adie.name %>. <%= link_to "DON'T PANIC.", "http://edgecats.net/" %> </h4>
  <% unless current_adie.ta %>
    <div class="btn btn-success" id='newProblem'>Create New Problem</div>
  <% end %>
</div>
<div class="queue_chart">
  <h2 id="fontFancy" class="center">Current Help Line </h2>
  <table id="projects" class="table">
    <thead>
      <tr>
        <th> # in line </th>
        <th> Adie, holla! </th>
        <th> Type of problem </th>
        <th> Time Estimate </th>
        <th> Description </th>
        <th> Helped? </th>
      </tr>
    </thead>
    <tbody> 
      <% @problems.sort_by {|problem| problem.created_at}.each_with_index do |problem, n| %>
        <tr>
          <td><%= n + 1 %></td>
          <td><%= image_tag(problem.adie.adatar_url, :width => 50, class: 'person') %>
          <%= problem.adie.name %></td>
          <td><%= problem.type %></td>
          <td><%= problem.estimate %></td>
          <td><%= problem.description %></td>
          <td>
            <% if session[:adie_id] == problem.adie_id && problem.helped == 'needs help' %>
              <%= button_to "I'm being helped!", helped_path(problem.id), class: "btn btn-small", id: 'help-button' %>
              <% elsif session[:adie_id] == problem.adie_id && problem.helped == 'being helped' %>
              <%= button_to "I've been helped!", helped_path(problem.id), class: "btn btn-small", id: 'help-button' %>
            <% end %> 
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'profile' %>
<%= render 'new_problem' %>

app/views/problems/new.html.erb
<%= render 'form' %>

app/views/problems/show.html.erb
<% @adie = Adie.find(@problem.adie_id) %>


<%= @adie.name %>'s problem:<br>

<strong>Type of problem:</strong> <%= @problem.type %><br>
<strong>Full Description: </strong><br><%= @problem.description %>
<br><br><br>

<% end %>