config/routes.rb
require 'resque/server'
HelpLine::Application.routes.draw do
  mount Resque::Server, :at => "/resque"
  root 'welcome#home'
  get 'sign-in',        to: 'welcome#home'
  post '/sign_in',      to: 'welcome#sign_in', as: :sign_in
  post '/sign_out',     to: 'welcome#sign_out', as: :sign_out

  get '/sign_up',       to: 'adies#new', as: :sign_up
  post '/sign_up',      to: 'adies#create', as: :add_adie # make only admin accessible?

  get '/analysis',      to: 'problems#analysis'
  get '/adies',         to: 'adies#index'

  get '/help_me',       to: 'problems#new'
  post '/help_me',      to: 'problems#create', as: :new_problem
  get '/problems',      to: 'problems#index', as: :problems
  get '/problems/:id',  to: 'problems#show', as: :problem
  post '/ratings/new',  to: 'ratings#create', as: :ratings
  post '/problems/:id', to: 'problems#update', as: :helped

  get '/profile',       to: 'adies#show', as: :profile
  patch '/profile',     to: 'adies#update', as: :set_profile
  patch '/reset',       to: 'adies#new_password', as: :forgot_password

  get '/status',        to: 'status#index'

  post '/csv',          to: 'adies#bulk_upload'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_filter :redirect_if_not_signed_in

  def home
    if current_adie
      redirect_to problems_path
    else
      @adie = Adie.new
    end
  end

  def sign_in
    adie = Adie.find(params[:name])
    if adie && adie.authenticate(params[:password])
      session[:adie_id] = adie.id
      redirect_to "/problems", notice: "You are now signed in!"
    else
      flash[:notice] = "Invalid password :("
      redirect_to '/'
    end
  end

  def sign_out
    session[:adie_id] = nil
    redirect_to root_path, notice: "You have successfully signed out!"
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_adies.html.erb
<%= form_tag sign_in_path do %>
<div class='sign-field'>
  <%= label_tag :name, nil, class: 'sign' %> 
  <%= select_tag :name, options_for_select(Adie.where(ta: false).sort_by {|unsorted_adie| unsorted_adie.name }.map { |adie| [adie.name, adie.id] }) %><br>
</div>
<div class='sign-field'>
  <%= label_tag :password, nil, class: 'pass' %> 
  <%= password_field_tag :password, params[:password] %><br>
</div>
<div class='sign-field'>
  <%= submit_tag "Sign-in!", class: "btn btn-success" %>
</div>
<% end %>

app/views/welcome/_tas.html.erb
<%= form_tag sign_in_path do %>
<div class='sign-field'>
  <%= label_tag :name, nil, class: 'sign' %> 
  <%= select_tag :name, options_for_select(Adie.where(ta: true).sort_by {|unsorted_adie| unsorted_adie.name }.map { |adie| [adie.name, adie.id] }) %><br>
</div>
<div class='sign-field'>
  <%= label_tag :password, nil, class: 'pass' %> 
  <%= password_field_tag :password, params[:password] %><br>
</div>
<div class='sign-field'>
  <%= submit_tag "Sign-in!", class:"btn btn-success" %>
</div>
<% end %>

app/views/welcome/home.html.erb
  <div class='row'>
    <div class="col-md-6">
      <h3>Are you an Adie?</h3>
        <%= render 'adies' %>
    </div>
    <div class="col-md-6">
      <h3> Are you a TA? </h3>
      <%= render 'tas' %>
    </div>
  </div>
  <div class='btn btn-link' id='forgot'>Forgot Your Password?</div>

  <div class="modal fade" id="forgotPassword" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" id="dismiss" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="fontFancy">Let's get you a new password!</h4>
      </div>
      <div class="modal-body">
        <%= render 'adies/password_request' %>
      </div>
      <div class="modal-footer">
        <button type="button" id="dismiss" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="createPassword">send</button>
      </div>
    </div>
  </div>
</div>