config/routes.rb
require 'resque/server'
HelpLine::Application.routes.draw do
  mount Resque::Server, :at => "/resque"
  root 'welcome#home'
  get 'sign-in',        to: 'welcome#home'
  post '/sign_in',      to: 'welcome#sign_in', as: :sign_in
  post '/sign_out',     to: 'welcome#sign_out', as: :sign_out

  get '/sign_up',       to: 'adies#new', as: :sign_up
  post '/sign_up',      to: 'adies#create', as: :add_adie # make only admin accessible?

  get '/analysis',      to: 'problems#analysis'
  get '/adies',         to: 'adies#index'

  get '/help_me',       to: 'problems#new'
  post '/help_me',      to: 'problems#create', as: :new_problem
  get '/problems',      to: 'problems#index', as: :problems
  get '/problems/:id',  to: 'problems#show', as: :problem
  post '/ratings/new',  to: 'ratings#create', as: :ratings
  post '/problems/:id', to: 'problems#update', as: :helped

  get '/profile',       to: 'adies#show', as: :profile
  patch '/profile',     to: 'adies#update', as: :set_profile
  patch '/reset',       to: 'adies#new_password', as: :forgot_password

  get '/status',        to: 'status#index'

  post '/csv',          to: 'adies#bulk_upload'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpLine</title>
      <link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
      <%= stylesheet_link_tag    "application", media: "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, user-scalable=no">
  </head>
  <body>
    <%= link_to image_tag('questionmark.png', height: 80, class: 'logo'), problems_path %>
    <div class='center'>
    <h1 id="fontFancy">Here, let me help you with that.</h1>
        <% if current_adie %>
        <span class='head_links'>
          <%= button_to 'Sign out', sign_out_path, class: "btn btn-default" %>
          <%= link_to 'Profile', profile_path, class: 'btn btn-default', id: 'profilePage', remote: true %>
          <% if current_adie.admin? %>
             <%= link_to 'Create An Adie', sign_up_path, class: 'btn btn-default', id: 'profilePage' %>
          <% end %>
          </span>
        <% else %>
          <br>
          <br>
        <% end %>
      </div>
    <hr>
    <div class="container">
      <div class='center flash_notice'>
        <%= flash.notice %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/statusboard.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
      <%= yield %>
  </body>
</html>